Started logging messages at Wed Jan 03 12:32:29 2018
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 70 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 56
Info:            Created 
Info:        Working on 78
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 75
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 18
Info:            Created 
Info:        Working on 125
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 26
Info:            Created 
Info:        Working on 156
Info:            Created 
Info:        Working on 191
Info:            Created 
Info:        Working on 39
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Working on 229
Info:            Created 
Info:        Working on 59
Info:            Created 
Info:        Working on 227
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 272
Info:            Created 
Info:        Working on 325
Info:            Created 
Info:        Working on 109
Info:            Created 
Info:        Working on 323
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 140
Info:            Created 
Info:        Working on 378
Info:            Created 
Info:        Working on 430
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 428
Info:            Created 
Info:        Working on 484
Info:            Created 
Info:        Working on 211
Info:            Created 
Info:        Working on 483
Info:            Created 
Info:        Working on 509
Info:            Created 
Info:        Working on 256
Info:            Created 
Info:        Working on 527
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 309
Info:            Created 
Info:        Working on 562
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 591
Info:            Created 
Info:        Working on 577
Info:            Created 
Info:        Working on 415
Info:            Created 
Info:        Working on 617
Info:            Created 
Info:        Working on 638
Info:            Created 
Info:        Working on 471
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 637
Info:            Created 
Info:        Working on 652
Info:            Created 
Info:        Working on 653
Info:            Created 
Info:        Working on 514
Info:            Created 
Info:        Working on 649
Info:            Created 
Info:        Working on 661
Info:            Created 
Info:        Working on 551
Info:            Created 
Info:        Working on 659
Info:            Created 
Info:        Working on 664
Info:            Created 
Info:        Working on 580
Info:            Created 
Info:        Working on 599
Info:            Created 
Info:        Working on 80
Info:            Created 
Info:        Working on 105
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 462
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 296
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 293
Info:            Created 
Info:        Working on 132
Info:            Created 
Info:        Working on 137
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 412
Info:            Created 
Info:        Working on 208
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Working on 302
Info:            Created 
Info:        Working on 548
Info:            Created 
Info:        Working on 357
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 464
Info:            Created 
Info:        Working on 566
Info:            Created 
Info:        Working on 383
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 618
Info:            Created 
Info:        Working on 492
Info:            Created 
Info:        Working on 534
Info:            Created 
Info:        Working on 568
Info:            Created 
Info:        Working on 593
Info:            Created 
Info:        Working on 433
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 487
Info:            Created 
Info:        Working on 498
Info:            Created 
Info:        Working on 279
Info:            Created 
Info:        Working on 281
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 575
Info:            Created 
Info:        Working on 394
Info:            Created 
Info:        Working on 449
Info:            Created 
Info:        Working on 500
Info:            Created 
Info:        Working on 537
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 389
Info:            Created 
Info:        Working on 596
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Working on 496
Info:            Created 
Info:        Working on 539
Info:            Created 
Info:        Working on 342
Info:            Created 
Info:        Working on 161
Info:            Created 
Info:        Working on 163
Info:            Created 
Info:        Working on 198
Info:            Created 
Info:        Working on 461
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 344
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 234
Info:            Created 
Info:        Working on 236
Info:            Created 
Info:        Working on 285
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Working on 341
Info:            Created 
Info:        Working on 399
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67617e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67963e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67617e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42148e-014
Info:            Rough distance of curve to surface: 1.77636e-015
Info:            Rough distance of curve to surface: 2.84217e-014
Info:            Rough distance of curve to surface: 2.84356e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.68461e-014
Info:            Rough distance of curve to surface: 2.86429e-014
Info:            Rough distance of curve to surface: 5.69543e-014
Info:            Rough distance of curve to surface: 5.69543e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.17782e-014
Info:            Rough distance of curve to surface: 3.17782e-014
Info:            Rough distance of curve to surface: 2.84217e-014
Info:            Rough distance of curve to surface: 2.99491e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.68617e-014
Info:            Rough distance of curve to surface: 5.68617e-014
Info:            Rough distance of curve to surface: 2.86429e-014
Info:            Rough distance of curve to surface: 2.39123e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.01755e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.1826e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.95778e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.95778e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.01755e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.01755e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.64013e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.1886e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.1826e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.1826e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.17764e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.1886e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.59872e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.59872e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.58882e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.08416e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84772e-014
Info:            Rough distance of curve to surface: 3.1826e-014
Info:            Rough distance of curve to surface: 3.1826e-014
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.59872e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.55316e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.13902e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.13902e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.17764e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.26096e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.26096e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.06581e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.58882e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.74951e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.74951e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:            Rough distance of curve to surface: 2.84217e-014
Info:            Rough distance of curve to surface: 5.85929e-014
Info:            Rough distance of curve to surface: 5.85929e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84356e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.6759e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67635e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67537e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67963e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67679e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.84217e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67821e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67395e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67635e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.6759e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67608e-011
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Wed Jan 03 12:32:30 2018
